[project]
name = "absolute-path-in-excludes"
version = "1.0.0"

[build-system]
requires = ["poexy-core"]
build-backend = "poexy_core.api"

[tool.poexy.package.absolute_path_in_excludes]
source = "src"
excludes = [
    "/workspace/tools/poexy-core/tests/samples/file_management/file_to_exclude.txt"
]
