name: 'Create Directory'
description: 'Create a directory'

inputs:
  path:
    description: 'The path to create'
    required: true
  parents:
    description: 'Create parent directories if they do not exist'
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Create directory
      shell: python
      run: |
        from pathlib import Path
        path = Path("${{ inputs.path }}")
        if "${{ inputs.parents }}" == "true":
            path.mkdir(parents=True, exist_ok=True)
        else:
            path.mkdir(exist_ok=True)