name: 'Set Mutex Environment'
description: 'Set Mutex Environment'

outputs:
  is-enabled:
    description: 'Whether mutex is enabled'
    value: ${{ steps.mutex.outputs.is-enabled }}

runs:
  using: composite
  steps:
    - name: Set Mutex Environment
      id: mutex
      shell: bash
      run: |
        if [ -z "${{ env.USE_MUTEX }}" ]; then
          USE_MUTEX="false"
        else
          if [ "${{ env.USE_MUTEX }}" == "true" ]; then
            USE_MUTEX="true"
          else
            USE_MUTEX="false"
          fi
        fi

        echo "is-enabled=$USE_MUTEX" >> $GITHUB_OUTPUT

        # Debug output
        echo "✅ USE_MUTEX: $USE_MUTEX"