name: 'Get Artifacts Registry Packages'
description: 'Get artifacts registry packages'

outputs:
  result:
    description: 'The packages'
    value: ${{ steps.packages.outputs.result }}

runs:
  using: composite
  steps:
    - name: Restore Artifacts Registry
      id: artifacts-registry
      uses: ./.github/actions/artifacts-registry/restore
      with:
        fail-on-cache-miss: true

    - name: Get Artifacts Registry Packages
      id: packages
      env:
        ARTIFACTS_REGISTRY_PATH: ${{ steps.artifacts-registry.outputs.path }}
      shell: bash
      run: |
        python ${{ github.action_path }}/main.py
