name: 'Initialize Mutex'
description: 'Initialize Mutex'

runs:
  using: composite
  steps:

    - name: Install AsyncPG
      shell: bash
      run: |
        pip install asyncpg

    - name: Init Mutex Table
      env:
        DATABASE_CONNECTION_URI: ${{ env.DATABASE_CONNECTION_URI }}
      working-directory: ${{ github.action_path }}
      shell: bash
      run: python main.py