[project]
name = "dependency-conflicting-local-hybrid"
version = "1.0.0"
dependencies = [
    "library @ ../library/"
]

[build-system]
requires = ["poexy-core"]
build-backend = "poexy_core.api"

[tool.poexy.package.dependency_conflicting_local_hybrid]
source = "src"

[tool.poexy.wheel]
format = ["source", "binary"]