name: 'Get Python Version'
description: 'Get Python version'

outputs:
  version:
    description: 'The Python version'
    value: ${{ steps.python-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Check installation
      shell: bash
      run: |
        if ! command -v python &> /dev/null; then
          echo "❌ Python is not installed. Please install it."
          exit 1
        fi

    - name: Set version output
      id: python-version
      shell: bash
      run: |
        PYTHON_VERSION=$(python --version | sed 's/Python //')
        echo "version=$PYTHON_VERSION" >> $GITHUB_OUTPUT
        echo "✅ Python version: $PYTHON_VERSION"