name: 'Release Registry Lock'
description: 'Release Registry Lock'

inputs:
  path:
    description: 'Path to the registry'
    required: true
    type: string
  key:
    description: 'Key to the registry'
    required: true
    type: string 

runs:
  using: composite
  steps:
    - name: Set environment variables
      id: registry
      uses: ./.github/actions/registry/set-env
      with:
        path: ${{ inputs.path }}
        key: ${{ inputs.key }}

    - name: Release Lock File
      id: release-lock-file
      env:
        LOCK_FILE: ${{ steps.registry.outputs.lock }}
      shell: bash
      run: |
        rm -f "$LOCK_FILE"
        echo "Lock file released at $LOCK_FILE"