name: 'Mutex Wait'
description: 'Wait for Mutex'

inputs:
  database-uri:
    description: 'The database URI'
    required: true
    type: string
  key:
    description: 'The key to wait for'
    required: true
    type: string
  holder:
    description: 'The holder to wait for'
    required: true
    type: string
  timeout:
    description: 'The timeout in seconds'
    required: false
    type: integer
    default: 60

runs:
  using: composite
  steps:
    - name: Setup CLI
      uses: ./.github/actions/mutex/setup

    - name: Wait for Mutex
      env: 
        DATABASE_URI: ${{ inputs.database-uri }}
      shell: bash
      run: |
        mutex-cli acquire \
          --key ${{ inputs.key }} \
          --holder ${{ inputs.holder }} \
          --timeout ${{ inputs.timeout }}