name: 'Setup Python Environment'
description: 'Setup Python, Pipx and Poetrydependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.13'
  os:
    description: 'Operating system'
    required: true
    default: 'ubuntu-latest'
  project-path:
    description: 'Path to the project'
    required: true
    default: '.'

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Generate pipx environment variables
      shell: bash
      run: |
        # Get user home directory
        HOME_DIR="$HOME"
        
        # Set pipx paths
        PIPX_HOME="$HOME_DIR/.local/pipx"
        PIPX_BIN_DIR="$PIPX_HOME/bin"
        
        # Create directories if they don't exist
        mkdir --parents "$PIPX_HOME"
        mkdir --parents "$PIPX_BIN_DIR"
        
        # Set environment variables
        echo "PIPX_HOME=$PIPX_HOME" >> $GITHUB_ENV
        echo "PIPX_BIN_DIR=$PIPX_BIN_DIR" >> $GITHUB_ENV
        
        # Add pipx bin directory to PATH
        echo "$PIPX_BIN_DIR" >> $GITHUB_PATH
        
        # Debug output
        echo "PIPX_HOME: $PIPX_HOME"
        echo "PIPX_BIN_DIR: $PIPX_BIN_DIR"
        echo "Github PATH:"
        cat $GITHUB_PATH

    - name: Restore Pipx cache
      id: cached-pipx
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.PIPX_HOME }}
        key: python-pipx-${{ runner.os }}-${{ inputs.python-version }}

    - name: Install pipx
      if: steps.cached-pipx.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python -m pip install --user pipx
        python -m pipx ensurepath

    - name: Install Poetry
      if: steps.cached-pipx.outputs.cache-hit != 'true'
      env:
        PIPX_HOME: ${{ env.PIPX_HOME }}
        PIPX_BIN_DIR: ${{ env.PIPX_BIN_DIR }}
      shell: bash
      run: |
        pipx install poetry

    - name: Save Pipx cache
      uses: actions/cache/save@v4
      with:
        path: ${{ env.PIPX_HOME }}
        key: steps.cached-pipx.outputs.cache-primary-key

    - name: Restore Poetry dependencies cache
      id: cached-poetry-dependencies
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.project-path }}/.venv
        key: python-poetry-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles(${{ inputs.project-path }}'/pyproject.toml') }}

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ inputs.project-path }}
      run: poetry install --only=main,dev

    - name: Save Poetry dependencies cache
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.project-path }}/.venv
        key: steps.cached-poetry-dependencies.outputs.cache-primary-key