name: 'Set Registry Environment Variables'
description: 'Set registry environment variables'

inputs:
  path:
    description: 'Path to the registry'
    required: true
    type: string
  key:
    description: 'Key to the registry'
    required: true
    type: string

outputs:
  path:
    description: 'The path to the registry'
    value: ${{ steps.registry.outputs.path }}
  key:
    description: 'The cache key for the registry'
    value: ${{ steps.registry.outputs.key }}
  self-path:
    description: 'The path to the self registry'
    value: ${{ steps.registry.outputs.self-path }}
  self-key:
    description: 'The cache key for the self registry'
    value: ${{ steps.registry.outputs.self-key }}

runs:
  using: composite
  steps:
    - name: Get home directory path
      uses: ./.github/actions/core/get-home-directory
      id: home-directory

    - name: Generate environment variables
      id: registry
      env:
        HOME_DIR: ${{ steps.home-directory.outputs.path }}
        REGISTRY_KEY: ${{ inputs.key }}
        REGISTRY_PATH: ${{ inputs.path }}
      shell: bash
      run: |        
        # Set paths
        REGISTRY_HOME="$HOME_DIR/.local/registry"
        REGISTRY_PATH="$REGISTRY_HOME/${{ env.REGISTRY_PATH }}"
        REGISTRY_KEY="registry-${{ github.run_id }}-${{ env.REGISTRY_KEY }}"
        SELF_REGISTRY_PATH="$REGISTRY_HOME/self"
        SELF_REGISTRY_KEY="registry-${{ github.run_id }}-self"

        # Set environment variables
        echo "path=$REGISTRY_PATH" >> $GITHUB_OUTPUT
        echo "key=$REGISTRY_KEY" >> $GITHUB_OUTPUT
        echo "self-path=$SELF_REGISTRY_PATH" >> $GITHUB_OUTPUT
        echo "self-key=$SELF_REGISTRY_KEY" >> $GITHUB_OUTPUT

        # Debug output
        echo "✅ REGISTRY_HOME: $REGISTRY_HOME"
        echo "✅ REGISTRY_PATH: $REGISTRY_PATH"
        echo "✅ REGISTRY_KEY: $REGISTRY_KEY"
        echo "✅ SELF_REGISTRY_PATH: $SELF_REGISTRY_PATH"
        echo "✅ SELF_REGISTRY_KEY: $SELF_REGISTRY_KEY"

    - name: Create Registry Path Directory
      uses: ./.github/actions/core/create-directory
      with:
        path: ${{ steps.registry.outputs.path }}
        parents: true

    - name: Create Self Registry Path Directory
      uses: ./.github/actions/core/create-directory
      with:
        path: ${{ steps.registry.outputs.self-path }}
        parents: true