name: 'Setup Python Pipx Environment'
description: 'Setup Python, Pipx and tools'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    type: string
  tools:
    description: 'Tools to install'
    required: true
    type: string
    default: '[]'

runs:
  using: composite
  steps:
    - name: Check tools is not empty list
      env:
        TOOLS: ${{ inputs.tools }}
      shell: bash
      run: |
        if [ -z "$TOOLS" ]; then
          echo "Tools list is empty"
          exit 1
        fi

    - name: Get home directory path
      uses: ./.github/actions/core/get-home-directory
      id: home-directory

    - name: Generate pipx environment variables
      shell: bash
      env:
        HOME_DIR: ${{ steps.home-directory.outputs.path }}
      run: |        
        # Set pipx paths
        PIPX_HOME="$HOME_DIR/.local/pipx"
        PIPX_BIN_DIR="$PIPX_HOME/bin"
        
        # Create directories if they don't exist
        mkdir --parents "$PIPX_HOME"
        mkdir --parents "$PIPX_BIN_DIR"
        
        # Set pipx environment variables
        echo "PIPX_HOME=$PIPX_HOME" >> $GITHUB_ENV
        echo "PIPX_BIN_DIR=$PIPX_BIN_DIR" >> $GITHUB_ENV
        
        # Add pipx bin directory to PATH
        echo "$PIPX_BIN_DIR" >> $GITHUB_PATH
        
        # Debug output
        echo "PIPX_HOME: $PIPX_HOME"
        echo "PIPX_BIN_DIR: $PIPX_BIN_DIR"
        echo "Github PATH:"
        cat $GITHUB_PATH

    - name: Restore Pipx cache
      id: cached-pipx
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.PIPX_HOME }}
        key: python-pipx-${{ runner.os }}-${{ inputs.python-version }}-with-${{ join( fromJSON(inputs.tools), '-' ) }}

    - name: Install pipx
      if: ${{ steps.cached-pipx.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        python -m pip install --user pipx
        python -m pipx ensurepath

    - name: Install tools
      if: ${{ steps.cached-pipx.outputs.cache-hit != 'true' }}
      env:
        PIPX_HOME: ${{ env.PIPX_HOME }}
        PIPX_BIN_DIR: ${{ env.PIPX_BIN_DIR }}
      shell: bash
      run: |
        pipx install ${{ join( fromJSON(inputs.tools), ' ' ) }}

    - name: Save Pipx cache
      if: ${{ steps.cached-pipx.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: ${{ env.PIPX_HOME }}
        key: ${{ steps.cached-pipx.outputs.cache-primary-key }}