name: 'Release Mutex Lock'
description: 'Release Mutex Lock'

inputs:
  key:
    description: 'Key of the mutex'
    required: true
    type: string 
  access-token:
    description: 'GitHub personal access token to access GitHub API'
    required: true

runs:
  using: composite
  steps:
    - name: Format Mutex Key
      id: format-mutex-key
      uses: ./.github/actions/mutex/format-key
      with:
        key: ${{ inputs.key }}

    - name: Release Mutex
      env:
        MUTEX_KEY: ${{ steps.format-mutex-key.outputs.key }}
        GH_TOKEN: ${{ inputs.access-token }}
      shell: bash
      run: |
        gh variable delete "$MUTEX_KEY" || exit 0
        echo "✅ Mutex released with key '$MUTEX_KEY'"