name: 'Format Mutex Key'
description: 'Format Mutex Key'

inputs:
  key:
    description: 'Key of the mutex'
    required: true
    type: string

outputs:
  key:
    description: 'Formatted key of the mutex'
    value: ${{ steps.format-mutex-key.outputs.key }}

runs:
  using: composite
  steps:
    - name: Format Mutex Key
      id: format-mutex-key
      env:
        MUTEX_KEY: ${{ inputs.key }}
      shell: python
      run: |
        import os

        mutex_key = "${{ env.MUTEX_KEY }}"

        for char in mutex_key:
          if char.isalnum() == False and char != '_':
            mutex_key = mutex_key.replace(char, '_')

        mutex_key = f'mutex_${{ github.workflow_sha }}_{mutex_key}'
        
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
          f.write(f'key={mutex_key}\n')