name: 'Poetry Install Dependencies'
description: 'Install dependencies with Poetry'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  dependency-groups:
    description: 'Dependency groups to install'
    required: true
    type: string
    default: '[]'

runs:
  using: composite
  steps:
    - name: Check if we are in a Poetry project
      working-directory: ${{ env.POETRY_PROJECT_PATH }}
      shell: bash
      run: |
        if [ ! -f "pyproject.toml" ]; then
          echo "❌ Error: Not in a Poetry project"
          exit 1
        fi

    - name: Check if poetry is installed
      shell: bash
      run: |
        if ! command -v poetry &> /dev/null; then
          echo "❌ Error: Poetry is not installed"
          exit 1
        fi

    - name: Check dependency groups is not empty list
      env:
        DEPENDENCY_GROUPS: ${{ inputs.dependency-groups }}
      shell: bash
      run: |
        if [ -z "$DEPENDENCY_GROUPS" ]; then
          echo "Dependency groups list is empty"
          exit 1
        fi

    - name: Get home directory path
      uses: ./.github/actions/core/get-home-directory
      id: home-directory

    - name: Generate poetry environment variables
      shell: bash
      env:
        HOME_DIR: ${{ steps.home-directory.outputs.path }}
      run: |  
        # Set poetry paths
        POETRY_HOME="$HOME_DIR/.local/poetry"
        POETRY_CACHE_DIR="$POETRY_HOME/cache"
        
        # Create directories if they don't exist
        mkdir --parents "$POETRY_HOME"
        mkdir --parents "$POETRY_CACHE_DIR"
        
        # Set poetry environment variables
        echo "POETRY_HOME=$POETRY_HOME" >> $GITHUB_ENV
        echo "POETRY_CACHE_DIR=$POETRY_CACHE_DIR" >> $GITHUB_ENV

        # Debug output
        echo "POETRY_HOME: $POETRY_HOME"
        echo "POETRY_CACHE_DIR: $POETRY_CACHE_DIR"

    - name: Get dependency groups hash
      id: dependency-groups-hash
      env:
        DEPENDENCY_GROUPS: ${{ join( fromJSON(inputs.dependency-groups), ',' ) }}
      shell: bash
      run: |
        DEPENDENCY_GROUPS_HASH=$(echo $DEPENDENCY_GROUPS | sha256sum | awk '{print $1}')
        echo "hash=$DEPENDENCY_GROUPS_HASH" >> $GITHUB_OUTPUT

    - name: Restore Poetry dependencies cache
      id: cached-poetry-dependencies
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.POETRY_CACHE_DIR }}
        key: python-poetry-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ steps.dependency-groups-hash.outputs.hash }}

    - name: Install dependencies
      if: ${{ steps.cached-poetry-dependencies.outputs.cache-hit != 'true' }}
      working-directory: ${{ env.POETRY_PROJECT_PATH }}
      shell: bash
      env:
        POETRY_CACHE_DIR: ${{ env.POETRY_CACHE_DIR }}
        DEPENDENCY_GROUPS: ${{ join( fromJSON(inputs.dependency-groups), ',' ) }}
      run: poetry install --only=$DEPENDENCY_GROUPS

    - name: Save Poetry dependencies cache
      if: ${{ steps.cached-poetry-dependencies.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: ${{ env.POETRY_CACHE_DIR }}
        key: ${{ steps.cached-poetry-dependencies.outputs.cache-primary-key }}