name: Python Poetry CD Pipeline

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: true
        type: string

env:
  PYTHON_VERSION: ${{ inputs.python-version }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs: 
  packages:
    name: Get Packages
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.packages.outputs.result }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Artifacts Registry Packages
        id: packages
        uses: ./.github/actions/artifacts-registry/packages

  release-draft:
    name: Create Release Draft
    needs: [packages]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: ${{ fromJSON(needs.packages.outputs.result) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: ${{ matrix.packages.name }} - Set Release Tag
        id: release-tag
        shell: bash
        run: |
          RELEASE_TAG=${{ matrix.packages.name }}-v${{ matrix.packages.version }}
          echo "result=${RELEASE_TAG}" >> $GITHUB_OUTPUT
          echo "✅ Release tag set to ${RELEASE_TAG}"

      - name: ${{ matrix.packages.name }} - Set Assets Path
        id: assets-path
        env: 
          ASSETS: ${{ matrix.packages.assets }}
        shell: python
        run: |
          import json
          import os
          assets = json.loads("${ASSETS}")
          asset = assets[0]
          asset_path = asset.parent
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"result={asset_path}\n")
          print(f"✅ Assets path set to {asset_path}")

      - name: ${{ matrix.packages.name }} - Create Release
        id: create-release
        shell: bash
        run: |
          # gh release create ${{ steps.release-tag.outputs.result }} --draft
          echo "✅ Release draft created with tag ${{ steps.release-tag.outputs.result }}"

      - name: ${{ matrix.packages.name }} - Upload Artifacts to Release
        id: upload-artifacts
        env:
          ASSETS: ${{ join(',', matrix.packages.assets) }}
        shell: bash
        run: |
          IFS="," read -a ASSETS <<< ${{ env.ASSETS }}
          for ASSET in "${ASSETS[@]}"; do
            echo "✅ Asset Uploaded: ${ASSET}"
          done
          # gh release upload ${{ steps.release-tag.outputs.result }} \
          #   ${{ matrix.packages.path }} \
          #   --clobber

      - name: ${{ matrix.packages.name }} - Setup Python Pipx Environment
        id: setup-pipx
        if: ${{ matrix.packages.type == 'poetry' }}
        uses: ./.github/actions/python/setup-pipx
        with:
          tools: poetry

      - name: ${{ matrix.packages.name }} - Dry-Run Pre-Release Commands
        id: dry-run-release-commands
        if: ${{ matrix.packages.type == 'poetry' }}
        env:
          COMMANDS: ${{ fromJSON(matrix.packages.pre_commands) }}
        shell: python
        run: |
          import json
          import os
          commands = json.loads("${{ env.COMMANDS }}")
          for command in commands:
            print(f"ℹ️ Executing command: {command}")
            os.system(command)
          print(f"✅ Pre-release commands executed successfully")

  clean-release-draft:
    name: Clean Release Draft
    if: ${{ always() && needs.release-draft.result == 'failure' }}
    needs: [packages, release-draft]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: ${{ fromJSON(needs.packages.outputs.result) }}
    steps:
      - name: ${{ matrix.packages.name }} - Set Release Tag
        id: release-tag
        shell: bash
        run: |
          RELEASE_TAG=${{ matrix.packages.name }}-v${{ matrix.packages.version }}
          echo "result=${RELEASE_TAG}" >> $GITHUB_OUTPUT
          echo "✅ Release tag set to ${RELEASE_TAG}"

      - name: ${{ matrix.packages.name }} - Delete Release Assets
        id: delete-release-assets
        env:
          ASSETS: ${{ join(',', matrix.packages.assets) }}
        shell: bash
        run: |
          IFS="," read -a ASSETS <<< ${{ env.ASSETS }}
          for ASSET in "${ASSETS[@]}"; do
            echo "✅ Asset Deleted: ${ASSET}"
          done
          # gh release delete-asset ${{ steps.release-tag.outputs.result }} \
          #   ${{ matrix.packages.path }} \
          #   --yes

      - name: ${{ matrix.packages.name }} - Delete Release Draft
        id: delete-release-draft
        shell: bash
        run: |
          # gh release delete ${{ steps.release-tag.outputs.result }} --yes --cleanup-tag
          echo "✅ Release draft deleted with tag ${{ steps.release-tag.outputs.result }}"

  release:
    name: Release
    if: ${{ always() && needs.release-draft.result == 'success' }}
    needs: [packages, release-draft]
    strategy:
      matrix:
        packages: ${{ fromJSON(needs.packages.outputs.result) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: ${{ matrix.packages.name }} - Set Release Tag
        id: release-tag
        shell: bash
        run: |
          RELEASE_TAG=${{ matrix.packages.name }}-v${{ matrix.packages.version }}
          echo "result=${RELEASE_TAG}" >> $GITHUB_OUTPUT
          echo "✅ Release tag set to ${RELEASE_TAG}"

      - name: ${{ matrix.packages.name }} - Edit Release
        id: edit-release-draft
        shell: bash
        run: |
          # gh release edit ${{ steps.release-tag.outputs.result }} --draft=false
          echo "✅ Release edited with tag ${{ steps.release-tag.outputs.result }}"

      - name: ${{ matrix.packages.name }} - Setup Python Pipx Environment
        id: setup-pipx
        if: ${{ matrix.packages.type == 'poetry' }}
        uses: ./.github/actions/python/setup-pipx
        with:
          tools: poetry

      - name: ${{ matrix.packages.name }} - Run Post-Release Commands
        id: post-release-commands
        if: ${{ matrix.packages.type == 'poetry' }}
        env:
          COMMANDS: ${{ fromJSON(matrix.packages.post_commands) }}
        shell: python
        run: |
          import json
          import os
          commands = json.loads("${{ env.COMMANDS }}")
          for command in commands:
            print(f"ℹ️ Executing command: {command}")
            # os.system(command)
          print(f"✅ Post-release commands executed successfully")

      - name: ${{ matrix.packages.name }} - Push Release
        id: push-release
        shell: bash
        run: |
          # git push
          echo "✅ Release pushed"