name: Python Poetry CD Pipeline

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: true
        type: string
      pipx-tools:
        description: 'Pipx tools to install'
        required: true
        type: string
      poetry-project-path:
        description: 'Path to the Poetry project'
        required: true
        type: string
      poetry-dependency-groups:
        description: 'Dependency groups to install'
        required: true
        type: string
      builds-registry-path:
        description: 'Path to the builds registry'
        required: true
        type: string
      builds-registry-key:
        description: 'Key to the builds registry'
        required: true
        type: string
      is-single-artifact:
        description: 'Whether the package is a single artifact'
        required: true
        type: boolean
        default: false

env:
  PYTHON_VERSION: ${{ inputs.python-version }}
  # Some composite actions related to Poetry are sensitive to working-directory,
  # but to simplify access to them, Poetry project path need to be set via an
  # environment variable defined globally.
  POETRY_PROJECT_PATH: ${{ inputs.poetry-project-path }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Commit Version Changes
        shell: bash
        run: |
          PROJECT_NAME=${{ steps.info.outputs.project-name }}
          PROJECT_VERSION=${{ steps.info.outputs.project-version }}
          echo "name: $PROJECT_NAME"
          echo "version: $PROJECT_VERSION"
          echo "commiting as ${{ github.actor }}"
          # git config --local user.email "action@github.com"
          # git config --local user.name "GitHub Action"
          # git add ${{ env.POETRY_PROJECT_PATH }}/pyproject.toml
          # git commit -m "chore(release): bump $PROJECT_NAME version to $PROJECT_VERSION"
          # git push 