name: CI/CD Pipeline

on:
  push:
    branches: [ main, ci-cd-pipeline ]
  pull_request:
    branches: [ main, ci-cd-pipeline ]

permissions:
  contents: write
  actions: write

jobs:
  matrix:
    name: Matrix Definitions
    runs-on: ubuntu-latest
    outputs:
      project-result: ${{ steps.set-project-matrix.outputs.result }}
      result: ${{ steps.set-matrix.outputs.result }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            poexy-core:
              - 'tools/poexy-core/**'
            ignite:
              - 'tools/ignite/**'

      - name: Set Project Matrix
        id: set-project-matrix
        env:
          POEXY_CORE_PROJECT_CHANGED: ${{ steps.filter.outputs.poexy-core }}
          IGNITE_PROJECT_CHANGED: ${{ steps.filter.outputs.ignite }}
        shell: python
        run: |
          import json
          import os
          poetry_projects = []
          pipx_tools = 'poetry'
          if '${{ env.POEXY_CORE_PROJECT_CHANGED }}' == 'true':
            poetry_projects.append({
              'path': 'tools/poexy-core',
              'pipx-tools': pipx_tools,
              'package-name': 'poexy-core',
              'dependency-groups': 'main, dev, test',
              'builds-registry-path': 'builds/',
              'builds-registry-key': 'builds-poexy-core',
              'is-single-artifact': 'true',
              'use-poexy-core': 'false',
              'use-mutex': 'false'
            })
          # if '${{ env.IGNITE_PROJECT_CHANGED }}' == 'true':
          #   poetry_projects.append({
          #     'path': 'tools/ignite',
          #     'pipx-tools': pipx_tools,
          #     'package-name': 'ignite',
          #     'builds-registry-path': 'builds/',
          #     'builds-registry-key': 'builds-ignite',
          #     'is-single-artifact': 'false',
          #     'use-poexy-core': 'true',
          #     'use-mutex': 'true'
          #   })
          matrix_data = json.dumps(poetry_projects)
          print(matrix_data)
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            f.write(f"result={matrix_data}\n")

      - name: Set Matrix
        id: set-matrix
        env:
          PROJECT_MATRIX: ${{ steps.set-project-matrix.outputs.result }}
        shell: python
        run: |
          import json
          import os
          poetry_projects = json.loads('${{ env.PROJECT_MATRIX }}')
          matrix = {
            "poetry-projects": poetry_projects,
            "os": [
              'ubuntu-latest', 
              # 'windows-latest', 
              # 'macos-latest'
            ],
            "python-version": [
              # '3.9', 
              # '3.10', 
              # '3.11', 
              # '3.12', 
              '3.13'
            ]
          }
          matrix_data = json.dumps(matrix)
          print(matrix_data)
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            f.write(f"result={matrix_data}\n")

  poetry-cicd:
    name: Poetry CI/CD - ${{ matrix.poetry-projects.package-name }} (${{ matrix.os }}-${{ matrix.python-version }})
    needs: [matrix]
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.result) }}
    uses: ./.github/workflows/python-poetry-cicd.yml
    with:
        os: ${{ matrix.os }}
        python-version: ${{ matrix.python-version }}
        pipx-tools: ${{ matrix.poetry-projects.pipx-tools }}
        poetry-project-path: ${{ matrix.poetry-projects.path }}
        poetry-package-name: ${{ matrix.poetry-projects.package-name }}
        poetry-dependency-groups: ${{ matrix.poetry-projects.dependency-groups }}
        builds-registry-path: ${{ matrix.poetry-projects.builds-registry-path }}
        builds-registry-key: ${{ matrix.poetry-projects.builds-registry-key }}
        use-poexy-core: ${{ matrix.poetry-projects.use-poexy-core == 'true' }}
        use-mutex: ${{ matrix.poetry-projects.use-mutex == 'true' }}
        is-single-artifact: ${{ matrix.poetry-projects.is-single-artifact == 'true' }}
    secrets:
      database-connection-uri: ${{ secrets.POSTGRESQL_CONNECTION_URI }}
      
