name: CI/CD Pipeline

on:
  push:
    branches: [ main, ci-cd-pipeline ]
    tags:
      - v*.*.*
  pull_request:
    branches: [ main, ci-cd-pipeline ]

permissions:
  # required for delete cache with gh cli extension
  # required for package job in python-poetry-ci.yml
  contents: read
  actions: write

jobs:
  init-package-registry:
    name: Init Package Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            .github  

      - name: Init Package Registry
        uses: ./.github/actions/package-registry/init

  matrix:
    name: Matrix Definition
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-matrix.outputs.result }}
    steps:
      - id: set-matrix
        shell: python
        run: |
          import json
          import os
          matrix = {
            "os": [
              'ubuntu-latest', 
              # 'windows-latest', 
              # 'macos-latest'
            ],
            "python-version": [
              # '3.9', 
              # '3.10', 
              # '3.11', 
              '3.12', 
              '3.13'
            ]
          }
          matrix_data = json.dumps(matrix)
          print(matrix_data)
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            f.write(f"result={matrix_data}\n")
  ci:
    name: CI (${{ matrix.os }} - Python ${{ matrix.python-version }})
    needs: [matrix, init-package-registry]
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.result) }}
    uses: ./.github/workflows/python-poetry-ci.yml
    with:
        os: ${{ matrix.os }}
        python-version: ${{ matrix.python-version }}
        poetry-project-path: 'tools/ignite'
        poetry-package-name: 'ignite'
  
  restore-package-registry:
    name: Restore Package Registry
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            .github  
      
      - name: Restore Package Registry
        id: package-registry
        uses: ./.github/actions/package-registry/restore

      - name: Show Package Registry
        run: cat ${{ steps.package-registry.outputs.file }}

  cd:
    name: CD
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Show Delivery Artifacts
        run: echo meowww !
      
