name: Python Poetry CD Pipeline

on:
  workflow_call

jobs:
  prepare-release:
    name: Prepare Package for Release
    runs-on: ubuntu-latest
    concurrency: ${{ github.workflow }}-prepare-release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Prepare Artifacts Registry for Release
        uses: ./.github/actions/artifacts-registry/prepare-release