name: Python Poetry CI Pipeline

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating system to run on'
        required: true
        type: string
      python-version:
        description: 'Python version to use'
        required: true
        type: string
      poetry-project-path:
        description: 'Path to the Poetry project'
        required: true
        type: string
      poetry-package-name:
        description: 'Name of the Poetry package'
        required: true
        type: string
      builds-registry-path:
        description: 'Path to the builds registry'
        required: true
        type: string
      builds-registry-key:
        description: 'Key to the builds registry'
        required: true
        type: string
    secrets:
      database-connection-uri:
        description: 'Database connection URI for mutex'
        required: true

env:
  PYTHON_VERSION: ${{ inputs.python-version }}
  # Some composite actions related to Poetry are sensitive to working-directory,
  # but to simplify access to them, Poetry project path need to be set via an
  # environment variable defined globally.
  POETRY_PROJECT_PATH: ${{ inputs.poetry-project-path }}

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/python/setup-python-pipx-poetry
        with:
          pipx-tools: '["poetry"]'
          poetry-dependency-groups: '["main", "dev"]'
        
  # tests:
  #   name: Tests
  #   runs-on: ${{ inputs.os }}
  #   needs: setup-environment
    
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Setup Environment
  #       uses: ./.github/actions/python/setup-python-pipx-poetry
  #       with:
  #         pipx-tools: '["poetry"]'
  #         poetry-dependency-groups: '["main", "dev"]'

  #     - name: Run Unit Tests
  #       uses: ./.github/actions/python/poetry/pytest
  #       with:
  #         test-path: tests/unit/
  #         run-in-parallel: true
  #         additional-pytest-options: --tb=short

  #     - name: Run Integration Tests
  #       uses: ./.github/actions/python/poetry/pytest
  #       with:
  #         test-path: tests/integration/
  #         run-in-parallel: true
  #         additional-pytest-options: --tb=short

  #     - name: Run Code Coverage
  #       id: code-coverage
  #       uses: ./.github/actions/python/poetry/pytest-code-coverage
  #       with:
  #         test-path: tests/
  #         coverage-report-format: xml
  #         coverage-artifact-name: coverage-report-${{ inputs.poetry-package-name }}
  #         coverage-artifact-path: coverage.xml
  #         upload-to-codecov: false
  #         run-in-parallel: true

  #     - name: Code Coverage Guard
  #       uses: ./.github/actions/python/code-quality/coverage-guard
  #       with:
  #         threshold: 95
  #         artifact-name: ${{ steps.code-coverage.outputs.coverage-artifact-name }}
  #         artifact-path: ${{ steps.code-coverage.outputs.coverage-artifact-path }}

  # code-quality:
  #   name: Code Quality
  #   runs-on: ${{ inputs.os }}
  #   needs: [setup-environment, tests]

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Setup Environment
  #       uses: ./.github/actions/python/setup-python-pipx-poetry
  #       with:
  #         pipx-tools: '["poetry"]'
  #         poetry-dependency-groups: '["main", "dev"]'

  #     - name: Check Linting
  #       id: linting
  #       continue-on-error: true
  #       uses: ./.github/actions/python/code-quality/flake8
  #       with:
  #         paths: ${{ inputs.poetry-package-name }}/ tests/

  #     - name: Check Code Formatting
  #       id: formatting
  #       continue-on-error: true
  #       uses: ./.github/actions/python/code-quality/black
  #       with:
  #         paths: ${{ inputs.poetry-package-name }}/ tests/

  #     - name: Check Import Sorting
  #       id: sorting
  #       continue-on-error: true
  #       uses: ./.github/actions/python/code-quality/isort
  #       with:
  #         paths: ${{ inputs.poetry-package-name }}/ tests/

  #     - name: Check All Code Quality Steps
  #       if: always()
  #       env:
  #         CODE_COVERAGE_OUTCOME: ${{ needs.tests.result == 'success' }}
  #         LINTING_OUTCOME: ${{ steps.linting.outcome == 'success' }}
  #         FORMATTING_OUTCOME: ${{ steps.formatting.outcome == 'success' }}
  #         SORTING_OUTCOME: ${{ steps.sorting.outcome == 'success' }}
  #       shell: bash
  #       run: |
  #         # Check if any of the code quality steps failed
  #         if [[ "$CODE_COVERAGE_OUTCOME" == "false" ]] || \
  #            [[ "$LINTING_OUTCOME" == "false" ]] || \
  #            [[ "$FORMATTING_OUTCOME" == "false" ]] || \
  #            [[ "$SORTING_OUTCOME" == "false" ]]; then
  #           echo "❌ One or more checks failed:"
  #           echo "  - Code coverage: $CODE_COVERAGE_OUTCOME"
  #           echo "  - Linting: $LINTING_OUTCOME"
  #           echo "  - Formatting: $FORMATTING_OUTCOME"
  #           echo "  - Import sorting: $SORTING_OUTCOME"
  #           exit 1
  #         else
  #           echo "✅ All checks passed!"
  #         fi
  
  build:
    name: Build
    runs-on: ${{ inputs.os }}
    needs: [setup-environment]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/python/setup-python-pipx-poetry
        with:
          pipx-tools: '["poetry"]'
          poetry-dependency-groups: '["main", "dev"]'

      - name: Bump Version
        uses: ./.github/actions/python/poetry/version  

      - name: Build Artifacts
        id: build-artifacts
        uses: ./.github/actions/python/poetry/build
        with:
          # build-script: build
          database-connection-uri: ${{ secrets.database-connection-uri }}

      - name: Wait for Build Mutex Release
        uses: ./.github/actions/mutex/wait
        with:
          key: ${{ inputs.builds-registry-key }}
          timeout: 60
          database-connection-uri: ${{ secrets.database-connection-uri }}

      - name: Restore Build Registry
        id: build-registry
        uses: ./.github/actions/registry/restore
        with:
          path: ${{ inputs.builds-registry-path }}
          key: ${{ inputs.builds-registry-key }}
          database-connection-uri: ${{ secrets.database-connection-uri }}

      - name: Add Build Artifacts to Build Registry
        env: 
          REGISTRY_PATH: ${{ steps.build-registry.outputs.path }}
          BUILD_ARTIFACTS_REGISTRY_KEY: ${{ steps.build-artifacts.outputs.artifacts-registry-key }}
        shell: bash
        run: |
          touch "$REGISTRY_PATH/$BUILD_ARTIFACTS_REGISTRY_KEY"
          if [ -f "$REGISTRY_PATH/$BUILD_ARTIFACTS_REGISTRY_KEY" ]; then
            echo "✅ Build artifacts added to registry"
          else
            echo "❌ Failed to add build artifacts to registry"
            exit 1
          fi

      - name: Release Build Mutex
        uses: ./.github/actions/mutex/release
        with:
          key: ${{ inputs.builds-registry-key }}
          database-connection-uri: ${{ secrets.database-connection-uri }}

      - name: Save Build Registry
        uses: ./.github/actions/registry/save
        with:
          path: ${{ inputs.builds-registry-path }}
          key: ${{ inputs.builds-registry-key }}
          database-connection-uri: ${{ secrets.database-connection-uri }}
          clean: true