name: Python Poetry CD Pipeline

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: true
        type: string
      poetry-project-path:
        description: 'Path to the Poetry project'
        required: true
        type: string
      builds-registry-path:
        description: 'Path to the builds registry'
        required: true
        type: string
      builds-registry-key:
        description: 'Key to the builds registry'
        required: true
        type: string
      is-single-artifact:
        description: 'Whether the package is a single artifact'
        required: true
        type: boolean
        default: false

env:
  PYTHON_VERSION: ${{ inputs.python-version }}
  # Some composite actions related to Poetry are sensitive to working-directory,
  # but to simplify access to them, Poetry project path need to be set via an
  # environment variable defined globally.
  POETRY_PROJECT_PATH: ${{ inputs.poetry-project-path }}
  POETRY_DEPENDENCY_GROUPS: main, dev, test
  
jobs:
  prepare-package:
    name: Prepare Package
    runs-on: ubuntu-latest
    # if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main'

    outputs:
      result: ${{ steps.build-artifacts-registry-keys.outputs.result }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Restore Build Registry
        id: build-registry
        uses: ./.github/actions/registry/restore
        with:
          path: ${{ inputs.builds-registry-path }}
          key: ${{ inputs.builds-registry-key }}

      - name: Prepare Artifacts Registry Keys
        id: build-artifacts-registry-keys
        working-directory: ${{ steps.build-registry.outputs.path }}
        shell: python
        run: |
          import json
          from pathlib import Path
          files = [path for path in Path.cwd().iterdir() if path.is_file()]
          if '${{ inputs.is-single-artifact }}' == 'true':
            runner_os = '${{ runner.os }}'
            for file in files:
              if runner_os in file.name:
                files = [file]
                break
          artifacts = []
          for file in files:
            with open(file, 'r', encoding='utf-8') as f:
              content = f.read()
            artifacts.append({
              "registry-path": content,
              "registry-key": file.name,
            })
          matrix = {
            "artifacts": artifacts
          }
          matrix_data = json.dumps(matrix)
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            f.write(f"result={matrix_data}\n")

  package:
    name: Package (${{ matrix.artifacts.registry-key }})
    needs: [prepare-package]
    runs-on: ubuntu-latest
    concurrency:
      group: packaging
      cancel-in-progress: false
    strategy:
      matrix: ${{ fromJSON(needs.prepare-package.outputs.result) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Restore Build Registry
        id: build-registry
        uses: ./.github/actions/registry/restore
        with:
          path: ${{ inputs.builds-registry-path }}
          key: ${{ inputs.builds-registry-key }}

      - name: Restore Artifacts Registry
        id: artifacts-registry
        uses: ./.github/actions/registry/restore
        with:
          path: ${{ matrix.artifacts.registry-path }}
          key: ${{ matrix.artifacts.registry-key }}

      - name: Copy Package
        working-directory: ${{ steps.build-registry.outputs.path }}
        shell: bash
        run: |
          LOCATION="artifacts" 
          mkdir --parents "$LOCATION"
          cp ${{ matrix.artifacts.registry-path }}/*.whl "$LOCATION/wheels"
          cp ${{ matrix.artifacts.registry-path }}/*.tar.gz "$LOCATION/source"

      - name: Save Build Registry
        uses: ./.github/actions/registry/save
        with:
          path: ${{ inputs.builds-registry-path }}
          key: ${{ inputs.builds-registry-key }}
          clean: true

  release:
    name: Release
    needs: [package]
    runs-on: ubuntu-latest
    # if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/python/setup-python-pipx-poetry
        with:
          python-version: ${{ inputs.python-version }}
          pipx-tools: '["poetry"]'
          poetry-dependency-groups: ${{ env.POETRY_DEPENDENCY_GROUPS }}

      - name: Bump Version
        uses: ./.github/actions/python/poetry/version  

      - name: Get Version
        id: info
        uses: ./.github/actions/python/poetry/info

      - name: Commit Version Changes
        run: |
          echo "version: ${{ steps.info.outputs.project-version }}"
          echo "commiting as ${{ github.actor }}"
          # git config --local user.email "action@github.com"
          # git config --local user.name "GitHub Action"
          # git add ${{ env.POETRY_PROJECT_PATH }}/pyproject.toml
          # git commit -m "chore(release): bump version to ${{ steps.info.outputs.project-version }}"
          # git push 