name: 'Setup Python Environment'
description: 'Setup Python, Pipx and Poetry dependencies'

runs:
  using: composite
  steps:
    - name: Check Python Version
      env:
        PYTHON_VERSION: ${{ env.PYTHON_VERSION }}
      shell: bash
      run: |
        if [ -z "$PYTHON_VERSION" ]; then
          echo "PYTHON_VERSION is not set"
          exit 1
        fi

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}