name: 'Setup Python Environment'
description: 'Setup Python, Pipx and Poetry dependencies'

runs:
  using: composite
  steps:
    - name: Check Python Version
      uses: ./.github/actions/python/check

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}